---
title: "R Notebook"
output: html_notebook
---

```{r include = F}
library(tidyverse)
library(sf)
library(rgdal)
library(janitor)
library(lubridate)
library(leaflet)
library(htmltools)
```

```{r include = F}
beds <- read_csv("raw_data/beds_specialty.csv")
```

```{r}
clean_beds <- beds %>% 
  clean_names() %>% 
  mutate(q = str_sub(quarter, -2)) %>% 
  # Change to date format
  mutate(quarter = yq(quarter)) %>% 
  # rename the columns above 
  mutate(date = quarter,
         quarter = q) %>% 
  mutate(location = if_else(location %in% "SB0801", "Golden Jubilee",
                      if_else(location %in% "S08000015", "Ayrshire & Arran",
                      if_else(location %in% "S08000016", "Borders",
                      if_else(location %in% "S08000017", "Dumfries & Galloway",
                      if_else(location %in% "S08000019", "Forth Valley",
                      if_else(location %in% "S08000020", "Grampian",
                      if_else(location %in% "S08000022", "Highland",
                      if_else(location %in% "S08000024", "Lothian",
                      if_else(location %in% "S08000025", "Orkney",
                      if_else(location %in% "S08000026", "Shetland",
                      if_else(location %in% "S08000028", "Western Isles",
                      if_else(location %in% "S08000029", "Fife",
                      if_else(location %in% "S08000030", "Tayside",
                      if_else(location %in% "S08000031", "Greater Glasgow & Clyde",
                      if_else(location %in% "S08000032", "Lanarkshire",
                      if_else(location %in% "S92000003", "Scotland", NA_character_ 
                            #  if_else(location %in% "^[A-Z0-9]{5}", , location)
                      ))))))))))))))))) %>% 
  filter(location != is.na(location)) %>% 
  # take out unused columns
  # take out location to remove duplicate
  select(date, quarter, hb, specialty_name, all_staffed_beds, 
         total_occupied_beds, average_available_staffed_beds,
         average_occupied_beds, percentage_occupancy) %>%
    rename(hb_name = hb)
rm(beds)
```

```{r}
filtered_beds <- clean_beds %>%
  filter(specialty_name == "Accident & Emergency",
         date == "2018-01-01",
         hb_name != "SB0801",
         hb_name != "S92000003") %>%
  rename(hb_code = hb_name)
```

```{r}
simplified_shapes <- st_transform(rmapshaper::ms_simplify(st_read(
  "raw_data/nhs_hb_2019/nhs_hb_2019.shp")),"CRS:84") %>%
  clean_names()
```

```{r}
merged <- sp::merge(simplified_shapes, filtered_beds) %>% 
  select(hb_name, percentage_occupancy, geometry)
```

```{r warning=FALSE}
pal <- colorBin("BuPu", domain = merged$percentage_occupancy)

merged %>%
  leaflet() %>%
  addTiles() %>%
  addProviderTiles(providers$OpenStreetMap) %>%
  addPolygons(
    fillColor = ~ pal(percentage_occupancy),
    weight = 2,
    opacity = 1,
    color = "white",
    dashArray = "3",
    fillOpacity = 0.7,
    highlight = highlightOptions(
      weight = 5,
      color = "#666",
      dashArray = "",
      fillOpacity = 0.7,
      bringToFront = TRUE),
    label = paste(merged$hb_name, ":", round(merged$percentage_occupancy)),
    labelOptions = labelOptions(
      style = list("font-weight" = "normal", padding = "3px 8px"),
      textsize = "15px",
      direction = "auto"),
    popup= paste0("<b>", htmlEscape(merged$percentage_occupancy), "%")) %>%
  addLegend("topleft", pal = pal, values = ~percentage_occupancy,
    title = "Percentage occupancy",
    opacity = 1) %>%
  addLayersControl(overlayGroups = c("Golden Jubilee", "Ayrshire & Arran", "Borders",
                                     "Dumfries & Galloway", "Forth Valley",
                                     "Grampian", "Highland", "Lothian", "Orkney", 
                                     "Shetland", "Western Isles", "Fife", 
                                     "Tayside", "Greater Glasgow & Clyde", 
                                     "Lanarkshire", "Scotland"), baseGroups = (providers$OpenStreetMap))
```
