---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(shinyWidgets)
library(janitor)
library(tidyverse)
library(leaflet)
library(tsibble)
library(shinythemes) # Themes maybe?
library(ggthemes)
library(infer)
library(shinydashboard)
library(tsibbledata)
library(fable)
library(slider)
library(feasts)
library(tidyquant)
library(sf)
library(rgdal)
library(lubridate)
library(sf)
library(rgdal)
library(leaflet)
```

```{r}
beds <- read_csv("beds_specialty.csv")

# read in shape file
hb_shapes <- st_read("SG_NHS_HealthBoards_2019/SG_NHS_HealthBoards_2019.shp")
```

```{r}
# cleaning script

beds_specialty_data <- beds %>% 
  clean_names() %>% 
  mutate(q = str_sub(quarter, -2),
         quarter = yq(quarter),
         date = quarter,
         quarter = q) %>%
  mutate(hb = if_else(hb %in% "S08000015", "Ayrshire & Arran",
              if_else(hb %in% "S08000016", "Borders",
              if_else(hb %in% "S08000017", "Dumfries & Galloway",
              if_else(hb %in% "S08000019", "Forth Valley",
              if_else(hb %in% "S08000020", "Grampian",
              if_else(hb %in% "S08000022", "Highland",
              if_else(hb %in% "S08000024", "Lothian",
              if_else(hb %in% "S08000025", "Orkney",
              if_else(hb %in% "S08000026", "Shetland",
              if_else(hb %in% "S08000028", "Western Isles",
              if_else(hb %in% "S08000029", "Fife",
              if_else(hb %in% "S08000030", "Tayside",
              if_else(hb %in% "S08000031", "Greater Glasgow & Clyde",
              if_else(hb %in% "S08000032", "Lanarkshire",
              if_else(hb %in% "S92000003", "Scotland", NA_character_)
              ))))))))))))))) %>% 
  filter(location_qf == "d") %>%
  # additional cleaning - to be added in
  filter(location != is.na(location)) %>% 
  select(date, quarter, hb, specialty_name, all_staffed_beds, 
         total_occupied_beds, average_available_staffed_beds,
         average_occupied_beds, percentage_occupancy) %>%
  rename(hb_name = hb)
  
```

```{r}
# plot from COVID tab

beds_specialty_data %>% 
  filter(specialty_name %in% c("All Acute", "All Specialties"),
         hb_name != "Scotland") %>%
  ggplot(aes(x = date, y = percentage_occupancy, col = specialty_name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~hb_name) +
  theme(legend.position="none")

```

## made acute_only just to try and plot on map to see if it would work

```{r}
# leaflet plots / tests from Pui

acute_only <- beds_specialty_data %>%
  filter(specialty_name == "All Acute",
         date == "2018-01-01",
         hb_name != "SB0801",
         hb_name != "S92000003") %>%
  rename(hb_code = hb_name)

# reduce the size of the shape file as it's quite big and takes forever to run
simplified <- rmapshaper::ms_simplify(hb_shapes)

# adds locations and coords for the polygon
simplified_2 <- st_transform(simplified,"CRS:84") %>%
  clean_names()

# merge with df
merged <- sp::merge(simplified_2, acute_only)
```


```{r}
# creating leaflet plot
  leaflet() %>%
    setView(lng = -5, lat = 57.35, zoom = 6) %>%
    # setMaxBounds(lng1 = -0.7,
    #              lat1 = 54.6,
    #              lng2 = -8.8,
    #              lat2 = 60.9) %>%
    addTiles() %>%
    addPolygons(data = simplified_2,
                fillColor = ~colorQuantile("Reds",merged$percentage_occupancy)(merged$percentage_occupancy),
                fillOpacity = 0.6,
                color = "darkgrey",      
                weight = 1.5)


# checking for regions
  leaflet() %>%
    setView(lng = -5, lat = 57.65, zoom = 5.7) %>%
    # setMaxBounds(lng1 = -0.7,
    #              lat1 = 54.6,
    #              lng2 = -8.8,
    #              lat2 = 60.9) %>%
    addTiles() %>%
    addPolygons(data = simplified_2,
                color = "green")

```

```{r}
merged_map_beds_data <- sp::merge(simplified_2, beds_specialty_data)

merged_map_beds_data %>%
  leaflet() %>%
    setView(lng = -5, lat = 57.65, zoom = 5.7) %>%
    # setMaxBounds(lng1 = -0.7,
    #              lat1 = 54.6,
    #              lng2 = -8.8,
    #              lat2 = 60.9) %>%
    addTiles() %>%
    addPolygons(data = simplified_2,
                color = "green")
```


